services:
  localstack:
    container_name: instagram
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:////var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
      # - SERVICES=lambda,apigateway,dynamodb,cloudformation.logs
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"